# Dynmap-WorldGuard configuration
#
update:
  # Seconds between checks for Residence updates
  period: 300

layer:
  name: "WorldGuard"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 0
  # (optional) set minimum zoom level before layer is visible (0 = defalt, always visible)
  minzoom: 0

# Set true to show 3D volumes for zones  
use3dregions: false

# Format for popup - substitute values for macros
infowindow: '<div class=\"infowindow\"><span style=\"font-size:120%;">%regionname% (%parent%) - %priority%</span><br /> Owners <span style="font-weight:bold;">%playerowners%<br/>%groupowners%</span><br/>Members <span style="font-weight:bold;">%playermembers%<br/>%groupmembers%</span><br/>Flags<br /><span style="font-weight:bold;">%flags%</span></div>'

regionstyle:
  strokeColor: "#FF0000"
  strokeOpacity: 0.8
  strokeWeight: 3
  fillColor: "#FF0000"
  fillOpacity: 0.35
  unownedStrokeColor: "#00FF00"

# Settings to disable the showing of specified regions on the map.
#
# Putting * at the start/end of a string hides regions in which names end/begin with the string.
#
# `prefix_*` hides regions whose names begin with `prefix_`, e.g. `prefix_1` `prefix_home`.
# `*_suffix` hides regions whose names end with `_suffix`, e.g. `1_suffix` `home_suffix`.
hidden-regions:
  default:
    - region_id_to_hidden
  world-name:
    - region_id_to_hidden

# Limit depth of child regions (1=just top regions, 2=top plus children of top)
maxdepth: 16

# Limit number of regions processed per tick (avoid lag spikes on servers with lots of regions)
updates-per-tick: 20
